### ISSUE TITLE
[Question] Migration Xamarin.Facebook.iOS to this library

### ISSUE THREAD

**Issue by frarcedev** [thisisthekap/Xamarin.FacebookSlim.iOS#5]
Hello, I'm working with the last version of Xamarin.Facebook.iOS 12 and version 11 on Android.

In my case only use the library to ActivateApp to log an app event for use in analytics and advertising reporting.

I call this in the AppDelegate.cs in this methods:

```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            Profile.EnableUpdatesOnAccessTokenChange(true);
            Settings.AppId = "XXXXXXXXXXX";
            Settings.DisplayName = "XXXXXX";

            ApplicationDelegate.SharedInstance.InitializeSdk();
        }

public override void OnActivated(UIApplication application)
        {
            AppEvents.Shared.ActivateApp();
        }
```

It's available this function in this library? I didn't find the documentation.

**Comment by thisisthekap** [comment]
@frarcedev Please reopen and clarify if still an issue.
